library(HandyCNV)

setwd("/Users/luciabazan/Documents/GitHub/cnv_sgdp")


### GRCh37

calls <- read.csv('data/cnvnator_cnvranger_input.csv', as.is=TRUE)

cnv_standard <- cnv_clean(standard_cnv = calls, #when running your own data, set this argument by 'standard_cnv = "localpath/file"'
                          drop_length = 5, #the maximum CNV length threshold (in Mb); CNVs larger than this value will be deleted
                          folder = "cnv_clean")
#> There are 365 individuals with 1239 CNVs i
#> 
#> 
#> 
#> 
cnv_visual(clean_cnv = cnv_penn_ars, #standard file was generated by 'cnv_clean' function in section 1
max_chr = 29, #select how many chromosomes to plot 
width_1 = 20, #optional,adjust the width of final plot
height_1 =12, #optional,adjust the height of final plot
folder = "cnv_visual_all_penn")


cnvr_cnvnator_ars <- call_cnvr(clean_cnv = cnv_standard, #standard file was generated by 'cnv_clean' function in section 1
                           chr_set = 42, #Set the maximum number of chromosomes (29 autosomes for cattle)
                           folder = "call_cnvr_grch37")

### CHM13 

calls <- read.csv('data/chm13_cnvranger_input.csv', as.is=TRUE)

cnv_standard <- cnv_clean(standard_cnv = calls, #when running your own data, set this argument by 'standard_cnv = "localpath/file"'
                          drop_length = 5, #the maximum CNV length threshold (in Mb); CNVs larger than this value will be deleted
                          folder = "cnv_clean_chm13")

cnvr_chm13 <- call_cnvr(clean_cnv = cnv_standard, #standard file was generated by 'cnv_clean' function in section 1
                               chr_set = 24, #Set the maximum
                               folder="calls_cnvr_chm13")

get_refgene()
                               
### distributipn map 
cnvr_plot(cnvr = "call_cnvr_chm13/cnvr.txt", #standard file was generated by 'call_cnvr' function in section 4
          assembly = "ARS", #cattle could select 'UMD' or 'ARS', other species could assign the name of species
          loss_col = "green2", #optional, adjust the color of Loss type of CNVR
          gain_col = "red", #optional, adjust the color of Gain type of CNVR
          mixed_col = "black",  #optional, adjust the color of Mixed type of CNVR
          legend_x = 127, #optional, adjust the horizontal position of legend
          legend_y = 30,  #optional, adjust the vertical position of legend
          #height_1 = 14, #optional, adjust the height of CNVR plot
          #width_1 = 10, #optional, adjust the width of CNVR plot
          folder = "cnvr_plot_penn")
                               
                               "