#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=1
#SBATCH --partition mctavish.q
#SBATCH --mem=120G
#SBATCH --time=0-120:00:00 #4 hrs

#SBATCH --output=penn_job_%j.stdout
#SBATCH --job-name=penn_cnvs
#SBATCH --export=ALL

whoami

#ad modules or conda environments here
module load anaconda3
source activate /home/jbazanwilliamson/anaconda3/envs/env

./software/PennCNV-Seq-master/convert_map2signal.pl /branchinecta/jbazanwilliamson/SAMEA3302866_chr1.bam /branchinecta/jbazanwilliamson/SGDP/reference/GRCh38_full_analysis_set_plus_decoy_hla.fa

